package:
  name: climextremes
  version: "0.2.0"

source:
  path: ../../python_wrapper

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
    - rpy2
  run:
    - r
    - python
    - setuptools
    - numpy
    - pandas
    - rpy2
    - clang_osx-64
    - clangxx_osx-64
    - gfortran_osx-64
    - r-devtools

test:
  imports:

about:
  home: https://bitbucket.org/lbl-cascade
  license: BSD
  license_file: LICENSE.txt
