{% set data = load_setup_py_data() %}

package:
  name: climextremes
  version: {{ data.get('version') }} 

source:
  path: ../../python_wrapper

build:
  noarch: python

requirements:
  build:
    - r >=3.0.0
    - python
    - setuptools
    - numpy
    - pandas
    - rpy2
    - tzlocal
  run:
    - r >=3.0.0
    - python
    - setuptools
    - numpy
    - pandas 
    - rpy2 
    - r-rcpparmadillo
    - tzlocal
    - r-devtools

test:
  imports:

about:
  home: https://bitbucket.org/lbl-cascade/climextremes-dev
  license: modified BSD
  license_file: LICENSE.txt
